# Generated by Django 5.1.6 on 2025-02-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='covers/')),
                ('background_color', models.CharField(max_length=7)),
                ('font_color', models.CharField(max_length=7)),
                ('font_size', models.IntegerField()),
                ('font_family', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
